dBildungsplattform/schulportal-client

src/plugins/vuetify.ts
See: https://ticketsystem.dbildungscloud.de/browse/SPSH-123
After deployment the nav links in the header are spaced again
=> bugfix: removed vuetify treeshaking to fix styles

src/services/ApiService.ts
/api -> /api/frontend
to make dev stage requests work
=> renamed api url

.github/workflows/image-publish-on-push-to-branch.yml, .github/workflows/image-publish-on-push-to-main.yml, package.json, sonar-project.properties, vite.config.ts
- Add sonarcloud to workflows
- Add sonarcloud configuration
- Configure tests to output a compatible coverage report
=> DBP-329-tests-sonar

.github/workflows/chart-release-manual.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> Dbp 394 chart version with timestamp

src/stores/PersonStore.spec.ts, src/stores/PersonStore.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-225
=> fix error handling for pw reset

src/components/admin/PasswordReset.vue, src/components/admin/UserTable.vue, src/locales/de-DE.json
- fixed translations for user table footer
- added missing test ids
see https://ticketsystem.dbildungscloud.de/browse/SPSH-309
=> Spsh 309 pagination translations

src/components/admin/PasswordReset.vue
cleared password copy hint after closing reset dialog
https://ticketsystem.dbildungscloud.de/browse/SPSH-322
=> SPSH 322 clear password hint after closing dialog

src/components/cards/LayoutCard.vue
- added a tabindex for close button
https://ticketsystem.dbildungscloud.de/browse/SPSH-328
=> SPSH 328 added tabindex for close button

.github/workflows/chart-release-manual.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
* increase the github workkflow versoin so that appVersion is cut to 7, this will help with the image Error Pull Back
=> DBP-559-test-rollout-of-helm-charts

vite.config.ts
Disables inlining of assets to fix the broken images due to strict CSP rules.
Widening of CSP rules was discussed but discarded.
=> SPSH-348 Disable inlining of assets

src/components/cards/LoginCard.vue
=> Fixed responsiveness

src/components/cards/LoginCard.vue, src/stores/AuthStore.spec.ts, src/stores/AuthStore.ts, src/stores/PersonStore.ts
- removed authInitialized prop
- link to start page is needed for reliable test, maybe wait for SPSH-214
https://ticketsystem.dbildungscloud.de/browse/SPSH-317
=> SPSH 317 auth for start page

src/layouts/DefaultLayout.spec.ts
we have to skip this test because injected vuetify layouts cannot be tested at the moment.
=> deployment hotfix

Dockerfile, README.md, src/components/layout/TheFooter.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-350
=> SPSH-350 add public folder to docker build

src/components/layout/TheFooter.vue
Fix for the footer on small screens.
=> Spsh 393 footer bottom bar

src/api-client/generated/api.ts, src/api-client/openapispec.json
Necessary API update
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/283
=> SPSH-367 Update API for ServiceProviders

src/components/admin/MenuBar.vue
=> SPSH-395-Close menu bar on item click.

Dockerfile
=> Pulled up builder image version

vite.config.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-432
=> calculate coverage only once

sonar-project.properties, vite.config.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-432
=> Spsh 432 coverage

public/impressum_datenschutzerklaerung.css
- Logo position fixed.
- Logo 20px bigger.
- Margin top and right fixed to bring the logo closer to the end of the layout.
=> Spsh 397 impr logo

sonar-project.properties, src/components/admin/MenuBar.vue, src/components/cards/LayoutCard.vue, src/components/cards/LoginCard.vue, src/locales/de-DE.json, src/views/StartView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-407
https://github.com/dBildungsplattform/schulportal-testautomatisierung/pull/9
=> SPSH 407 added missing test ids

charts/spsh-client/values.yaml
=> Made PullPolicy reflect the fact that we're still in Development

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
add a description and rename workflwo file - so it is easier to have an overview of failed jobs in the PR overview
=> DBP-631-rename-workflow-file

.github/workflows/chart-release-manual.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> Dbp 625 update spsh to use a new versioning

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-623 Cross branch rollout

src/views/admin/PersonManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-473
=> SPSH 473 added username to result table again

.github/workflows/create-release.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
- add a GHA so that a GHCR Image and Helm Chart to helm-charts-registry are released based on the pushed tag
=> DBP-679-create-release-gha

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> Dbp 696 fix playwright tests

src/services/ApiService.ts
Fix for interceptor to redirect users to the login page upon receiving a 401 Unauthorized.
https://ticketsystem.dbildungscloud.de/browse/SPSH-479
=> SPSH-479-interceptor-fix

Dockerfile
=> Removed update command once needed because of trivy

Dockerfile
https://ticketsystem.dbildungscloud.de/browse/DBP-705
Fix :
ERROR: failed to solve: process "/bin/sh -c apk add libexpat=2.6.0-r0 && rm -rf /var/cache/apk/" did not complete successfully: exit code: 4 Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apk add libexpat=2.6.0-r0 && rm -rf /var/cache/apk/" did not complete successfully: exit code: 4
change alpine/libexpat 2.6.0-r0 to alpine/libexpat 2.6.2-r0
https://hub.docker.com/layers/library/nginx/1.25-alpine/images/sha256-f461411180b06f2a9f339814bc59bc187db074f6adb16e08287a196db50276de?context=explore
=> Dbp 705 build failure due to apk add libexpat command in docker build process

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml, Dockerfile, charts/schulportal-client/templates/deployment.yaml, charts/schulportal-client/values.yaml, nginx-vue.conf
https://ticketsystem.dbildungscloud.de/browse/DBP-620
=> Dbp 620 run nginx container asnonrootuser

src/views/admin/RolleCreationView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-417
=> spsh 417 test ids

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-647-small-improvements

src/views/admin/SchuleCreationView.vue
Fixed validation for Schulname.
https://ticketsystem.dbildungscloud.de/browse/SPSH-531
=> SPSH-531-schulname-validation

charts/schulportal-client/templates/_helpers.tpl, charts/schulportal-client/templates/deployment.yaml, charts/schulportal-client/templates/ingress.yaml, charts/schulportal-client/templates/service.yaml, charts/schulportal-client/values.yaml
=> DBP-686-clean-helm-chart

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml, src/components/cards/ServiceProviderCard.vue, src/styles/components/service-provider-card.scss, src/views/StartView.vue
Padding right to the v-card.
Images with a big aspect ratio appear smaller. Solution? 
https://ticketsystem.dbildungscloud.de/browse/SPSH-532
=> SPSH-532-startseite-darstellung

src/stores/OrganisationStore.ts, src/views/admin/RolleCreationView.vue, src/views/admin/RolleManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-476
=> handle empty Kennung in Organisation

src/views/admin/PersonCreationView.vue, src/views/admin/RolleCreationView.vue, src/views/admin/SchuleCreationView.vue
Added test ids for https://github.com/dBildungsplattform/schulportal-testautomatisierung/pull/18
=> spsh-508 added test ids for creation success

Dockerfile
Cherry-picked trivy fix commits from SPSH-542
https://ticketsystem.dbildungscloud.de/browse/SPSH-621
If pipeline succeeds, this can be merged
=> Spsh 621 trivy fix

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
Motivation:
An error is occurring when attempting to delete a namespace within schulportal-client
To do list:
Debug Namespace Deletion Process
Test Deletion{}
Acceptance criteria (testable):
The namespace can be deleted without encountering errors.
=> Ops 6358 resolve erreur deleting namespace

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/locales/de-DE.json, src/stores/OrganisationStore.spec.ts, src/stores/OrganisationStore.ts, src/stores/PersonStore.ts, src/stores/PersonenkontextStore.spec.ts, src/views/admin/PersonDetailsView.vue, src/views/admin/PersonManagementView.spec.ts, src/views/admin/PersonManagementView.vue
Added Kopers-Nr to the Table.
Added Kopers-Nr to the personDetails.
https://ticketsystem.dbildungscloud.de/browse/SPSH-574
=> SPSH-574-kopersnr

src/views/admin/PersonManagementView.vue
Changed the order of the column for kopersnr.
https://ticketsystem.dbildungscloud.de/browse/SPSH-634
=> SPSH-634-fix-kopersnr

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/components/admin/MenuBar.vue, src/components/admin/ResultTable.vue, src/components/admin/SearchField.spec.ts, src/components/admin/SearchField.vue, src/locales/de-DE.json, src/stores/OrganisationStore.spec.ts, src/stores/PersonStore.spec.ts, src/stores/PersonStore.ts, src/stores/PersonenkontextStore.spec.ts, src/views/admin/PersonManagementView.vue, src/views/admin/RolleCreationView.vue, src/views/admin/RolleManagementView.vue, src/views/admin/SchuleManagementView.vue
New component SearchField.vue that emits a string to the parent component (Could be any Management View).
https://ticketsystem.dbildungscloud.de/browse/SPSH-554
=> SPSH-554-suche-benutzer

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/stores/PersonStore.ts
Newest spec where search strings are optional.
https://ticketsystem.dbildungscloud.de/browse/SPSH-644
=> SPSH-644-searchstring-optional

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/stores/OrganisationStore.ts, src/views/admin/RolleCreationView.vue
=> SPSH-661 exclude klassen from organisationen

src/components/cards/LoginCard.vue
Removed container to adjust welcome text
https://ticketsystem.dbildungscloud.de/browse/SPSH-677
=> spsh 677 adjusted welcome text

src/styles/components/result-table.scss, src/styles/main.scss, src/views/admin/PersonManagementView.vue, src/views/admin/RolleManagementView.vue, src/views/admin/SchuleManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-615
=> SPSH-615-tooltip-ellipsis

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
Reference deploy.yaml with tag 4.0.0
=> Dbp 757 playwright tests

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
use tag 4.0.0  instead of branch name
=> OPS-000-Use tag 4.0.0 instaed or branch name

src/stores/PersonStore.ts
=> Fixed test

src/views/admin/PersonManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-690
=> SPSH-690-zuordnungen-liste

Dockerfile, src/api-client/generated/api.ts, src/api-client/openapispec.json, src/components/admin/PersonDelete.spec.ts, src/components/admin/PersonDelete.vue, src/locales/de-DE.json, src/stores/AuthStore.ts, src/stores/PersonStore.ts, src/views/admin/PersonDetailsView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-666
=> SPSH-666-benutzer-loeschen

src/stores/OrganisationStore.spec.ts, src/stores/OrganisationStore.ts, src/views/admin/KlasseCreationView.spec.ts, src/views/admin/KlasseCreationView.vue, src/views/admin/SchuleCreationView.spec.ts, src/views/admin/SchuleCreationView.vue
split created organisation into schule and klasse
https://ticketsystem.dbildungscloud.de/browse/SPSH-749
=> SPSH 749 split created organisation into schule and klasse

src/views/admin/KlasseCreationView.vue, src/views/admin/SchuleManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-762
=> Spsh 762 only show admins editable schulen

src/views/admin/RolleCreationView.vue
remove migration permission from systemrechte
https://ticketsystem.dbildungscloud.de/browse/SPSH-774
=> spsh 774 filter migration permission from system permissions

src/views/admin/PersonManagementView.vue
reset klasse filter after schule selection
https://ticketsystem.dbildungscloud.de/browse/SPSH-797
=> spsh 797 reset klasse filter after schule selection

src/locales/de-DE.json, src/router/routes.ts, src/views/UnknownUserErrorView.spec.ts, src/views/UnknownUserErrorView.vue
=> SPSH-387 Add unknown user error page

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
- update Dev Pipeline to Version 5 to also rollout the Ldap Server
=> DBP-799-openldap-image-helm-chart

src/views/admin/KlassenManagementView.vue, src/views/admin/PersonManagementView.vue
=> SPSH-857-filter-fix

src/stores/OrganisationStore.spec.ts, src/stores/OrganisationStore.ts
=> fixed limit

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-952-improvements-database-deletion-job

LICENSE, package.json
=> DBP-952 add license file

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/locales/de-DE.json, src/stores/AuthStore.spec.ts, src/stores/AuthStore.ts
=> SPSH-1136 Add systemrecht for person sync

package-lock.json, package.json
https://ticketsystem.dbildungscloud.de/browse/SPSH-???
=> Changed version to current dev version of 0.6.0

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-0000-improve-speed-of-pipeline

charts/schulportal-client/templates/deployment.yaml, charts/schulportal-client/templates/hpa.yaml, charts/schulportal-client/values.yaml
=> Dbp 1021 adapt spsh helm charts for autoscaling

src/components/form/FormWrapper.vue, src/views/admin/PersonDetailsView.vue, src/views/admin/PersonImportView.vue
moved upload success template into form to be able to trigger unsaved changes dialog from there
https://ticketsystem.dbildungscloud.de/browse/SPSH-1347
=> SPSH-1347 Ungespeicherte Änderungen beim CSV-Import nach dem Upload

src/views/admin/PersonDetailsView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-1493
=> SPSH-1493-fix icon alignment

src/components/admin/personen/PasswordReset.vue, src/locales/de-DE.json
changed pw reset message and fixed pw output width
https://ticketsystem.dbildungscloud.de/browse/SPSH-1408
=> SPSH 1408 Hinweistext bei Passwort zurücksetzen ergänzen

src/components/cards/LoginCard.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-1551
=> fix date for maintenance period warning

public/impressum_datenschutzerklaerung.html
changed wording for legal notice and privacy page
https://ticketsystem.dbildungscloud.de/browse/SPSH-1545
=> Spsh 1545 Impressum Anpassen

src/stores/OrganisationStore.ts, src/views/admin/KlassenManagementView.vue, src/views/admin/PersonDetailsView.vue, src/views/admin/PersonManagementView.vue
removed computed for dropdown options and replaced it with ref that is filled after every request
https://ticketsystem.dbildungscloud.de/browse/SPSH-1552
=> SPSH-1552: Fehler im Klassenfilter (Benutzerliste)

charts/schulportal-client/templates/ingress.yaml
=> DBP-1147-ingress-https-release

charts/schulportal-client/templates/ingress2nd.yaml, charts/schulportal-client/values.yaml
Add secondary Ingress if enabled
=> Dbp 1105 2nd ingress

charts/schulportal-client/templates/pdb.yaml, charts/schulportal-client/values.yaml, src/locales/de-DE.json
=> DBP-1158-Create-PodDisruptionBudget-for-SPSH-Applications

charts/schulportal-client/values.yaml
=> DBP-1204-fix-pdb Changed min available percentage to a more realistic value

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
https://ticketsystem.dbildungscloud.de/browse/SPSH-1696
=> Update deploy workflow

src/views/admin/PersonDetailsView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-1698
=> SPSH 1698 reset kopersnr checkbox after addition of schulzuordnung

src/views/admin/PersonDetailsView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-1700
=> SPSH 1700 update personalnummer after adding it with a new zuordnung

src/views/admin/PersonManagementView.vue
- apply searchFilters and sorting after fetching persons paginated (with and without limit)
Base links to copy
- https://github.com/dBildungsplattform/schulportal-client/pulls
- https://ticketsystem.dbildungscloud.de/browse/SPSH-1788
=> SPSH-1788: Apply SearchFilters and Sorting after fetching persons

.github/workflows/create-release.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-1264-improve-pipeline-remove sonar from releasing image

Dockerfile
https://ticketsystem.dbildungscloud.de/browse/SPSH-1979
https://github.com/dBildungsplattform/schulportal-client/security/code-scanning/515
=> SPSH 1979 fix trivy warnings

Dockerfile
Fix security warnings from Trivy
https://ticketsystem.dbildungscloud.de/browse/SPSH-2002
=> SPSH 2002 fix trivy alerts

Dockerfile
https://ticketsystem.dbildungscloud.de/browse/SPSH-2067
=> SPSH 2067 fix trivy warning

src/components/admin/klassen/KlasseForm.vue, src/views/admin/organisationen/KlasseCreationView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-1920
=> SPSH-1920 Bei Klassenanlage die ausgewählte Schule merkenset selected schule as initial value after submit

src/components/layout/TheHeader.vue, src/router/index.ts, src/stores/AuthStore.spec.ts, src/stores/AuthStore.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1999
=> initialize AuthStore less often

src/views/admin/PersonDetailsView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-2031
=> SPSH-2031 Befristung bestehender Schulzuordnung fehlt auf der Zusammenfassungsseite

src/components/admin/personen/PersonenkontextCreate.vue
=> SPSH-2161: fix bug

src/api-client/generated/api.ts, src/api-client/openapispec.json, src/components/admin/personen/PersonenkontextCreate.spec.ts, src/components/admin/personen/PersonenkontextCreate.vue, src/components/admin/rollen/RolleModify.vue, src/components/admin/rollen/RolleUnassign.vue, src/stores/PersonStore.spec.ts, src/stores/PersonenkontextStore.spec.ts, src/stores/PersonenkontextStore.ts, src/views/admin/PersonCreationView.vue, src/views/admin/PersonDetailsView.vue, src/views/admin/PersonImportView.vue, src/views/admin/PersonManagementView.vue, src/views/admin/PersonSearchView.spec.ts
- updated API with `operationContext` for `personenkontext-workflow`, so BE can check permissions properly
=> SPSH-2189: OperationContext for PersonenkontextWorkflow

src/components/admin/personen/details/PersonenkontextItem.spec.ts, src/components/admin/personen/details/PersonenkontextItem.types.ts, src/components/admin/personen/details/PersonenkontextItem.vue, src/views/admin/PersonDetailsView.vue, src/views/admin/PersonImportView.vue
=> SPSH-2167: add missing check to prevent navigation

src/views/admin/PersonCreationView.vue, src/views/admin/PersonManagementView.vue
https://ticketsystem.dbildungscloud.de/browse/SPSH-2389
=> SPSH-2389-EBF

.github/workflows/chart-release-manual.yml, .github/workflows/create-release.yml, .github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
=> DBP-1657-Update Sonarqube GHA to 5.3.1

src/stores/RolleStore.spec.ts, src/stores/RolleStore.ts, src/views/admin/rollen/RolleCreationView.vue, src/views/admin/rollen/RolleDetailsView.vue
=> SPSH-2728: fix bug with Angebote not showing up in RolleDetailsView
